### ISSUE TITLE
indexDB support ?

### ISSUE THREAD

**Issue by MentalGear** [nitaiaharoni1/vector-storage#8]
First thanks for the awesome library!

Its great that you have added automatic eviction if storage is too low, but sometimes one wants to store more data.

Would it be possible to add indexDB support, possible even add an option to auto-switch to indexDB if the localStorage db is exceeded?

Another idea is to store items automatically in indexed if normal storage is exceeded, and only look in the indexDB for retrieval if result similarity is under a certain threshold within local storage.

**Comment by MentalGear** [comment]
Sorry, mixed this library with another lib.

**Comment by Nithur-M** [comment]
hello @MentalGear may I know the name of that lib?

**Comment by MentalGear** [comment]
tbh, I'm not sure, but the one I started working with is "voy-search".

**Comment by Nithur-M** [comment]
> tbh, I'm not sure, but the one I started working with is "voy-search".

Thanks, I also looked into it. Can it work with OpenAI? can I access the stored index again?
